/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'SAFETYAI',systemName:'知华作业安全 AI 平台',englishName:'WORKPLACE SAFETY AI',theme:{primary:'#2f6657',dark:'#203c36',accent:'#d88945'},
 workspace:'安全生产中心 / 风险智能组',fieldWorkspace:'华东基地 / 现场安全组',period:'2026-08-15 · 实时管控',liveText:'作业风险于 10:31 更新',fieldContextLabel:'当前班次',fieldContext:'白班 08:00—17:00',fieldUser:'程野',fieldRole:'现场安全员',adminUser:'梁安',adminRole:'安全运营负责人',
 adminTitle:'作业安全指挥中心',adminBreadcrumb:'安全智能 / 全场态势',adminSubtitle:'融合工作票、人员资质、环境和现场检查，形成可解释的作业放行建议与安全门禁。',exportAction:'导出安全报告',createAction:'新建评估任务',
 chartTitle:'风险治理闭环趋势',chartSubtitle:'本月闭环率 / 安全目标',chartLabels:['01日','05日','09日','13日','17日','21日','25日','29日','31日'],loadTitle:'区域风险负荷',loadSubtitle:'高风险作业占当前在场任务比例',recordsTitle:'重点作业风险任务',recordsSubtitle:'按风险评分、作业等级和影响范围排序',issueTitle:'需要处理的安全风险',issueSubtitle:'来自工作票、人员、环境和防护检查',
 recordName:'评估任务',itemName:'作业许可',unitName:'责任班组',batchName:'风险来源',planName:'检查项',doneName:'已确认',exceptionName:'隐患',unitLabel:'项',
 listBreadcrumb:'作业安全 / 风险任务',listSubtitle:'将作业类型、人员资质、环境和防护措施汇总为可解释的放行判断。',listSummary:[['在场作业','73'],['今日评估','46'],['停止放行','6',true],['已闭环','29']],tabs:['全部','待评估','整改中','待复核','已归档'],
 fieldBreadcrumb:'现场工作台 / 安全员',fieldTitle:'作业安全工作台',fieldSubtitle:'负责区域 3 个 · 今日巡检 15 项 · 待处理隐患 5 条',fieldSecondary:'查看巡检路线',reportAction:'提交检查结论',fieldNoticeTitle:'现场感知链路正常',fieldNotice:'关键区域覆盖率 96.2%',
 steps:['许可接入','风险识别','措施校验','人工放行','闭环复盘'],documentAction:'查看作业档案',printAction:'导出安全检查单',resourceCardTitle:'安全感知资源',resourceValueLabel:'在线点位',resourceHealthLabel:'感知健康度',quickSubtitle:'常用安全入口',
 quickActions:[['风险评估','/shopfloor/report','作业、人员与环境证据'],['作业档案','/shopfloor/material','工作票、承包商和资质'],['感知资源','/shopfloor/resources','视频、气体检测和模型'],['隐患升级','/shopfloor/andon','停止作业与跨部门整改']],
 reportDefaults:[7,2],reportTitle:'现场安全检查',reportSubtitle:'记录风险点、控制措施和放行建议。',reportSuccess:'安全检查结论已提交',reportPlaceholder:'填写现场情况、隐患位置、控制措施和复核要求',reportFootnote:'提交后进入安全运营负责人复核队列',ruleTitle:'高风险作业放行门禁',ruleSubtitle:'SAFETY-AI · V1.0',rules:[['高风险作业','必须人工审批'],['人员资质','证书有效可追溯'],['现场证据','保留原始记录'],['整改闭环','复工前复核',true]],fieldTotals:[['15','今日巡检'],['5','待处理隐患'],['73','在场作业'],['96.2%','感知覆盖率']],
 adminMenus:[['/admin','home','安全指挥中心'],['/admin/work-orders','order','风险任务'],['/admin/samples','box','作业许可'],['/admin/schedule','calendar','巡检计划'],['/admin/methods','process','风险规则'],['/admin/reviews','quality','放行复核'],['/admin/resources','machine','感知资源'],['/admin/report','chart','安全分析']],fieldMenus:[['/shopfloor','home','安全工作台'],['/shopfloor/report','report','现场检查'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','作业档案'],['/shopfloor/resources','machine','感知状态'],['/shopfloor/andon','risk','隐患升级',5]],
 moduleTitles:{tasks:['我的风险任务','查看等级、区域和整改状态'],material:['作业许可档案','查看工作票、人员和控制措施'],resources:['安全感知中心','管理视频、传感器和风险模型'],andon:['安全隐患升级','提交停止作业和协同整改'],samples:['作业许可台账','统一管理高风险作业与承包商'],schedule:['安全巡检计划','协调区域、人员和复核时段'],methods:['风险识别规则','维护阈值、作业类型和措施库'],reviews:['作业放行复核','记录通过、驳回和补充检查'],report:['安全运营分析','分析隐患、违章和闭环效率']},
 tagline:'让每一次作业放行，都有证据与责任边界',storyTitle:'把现场风险，<br/>变成可执行的安全门禁',storyText:'融合工作票、人员资质和环境信号，帮助安全团队提前阻断风险，坚持人工最终放行。',pattern:[3,5,8,11,14,17,20,23,26,29,31],loginStats:[['73','在场作业'],['96.2%','感知覆盖率'],['6','停止放行']],loginTitle:'作业安全指挥中心',adminDemo:'风险 / 作业 / 闭环',fieldDemo:'巡检 / 隐患 / 放行'}
export const records=[{no:'SA-260815-018',name:'罐区受限空间检修',code:'WP-260815-09',unit:'设备检修一组',group:'储运罐区',plan:14,done:8,exception:4,due:'08-15',batch:'工作票+气体',status:'整改中',progress:57,priority:'停止'},{no:'SA-260815-021',name:'锅炉房高处保温作业',code:'WP-260815-21',unit:'公用工程组',group:'能源中心',plan:11,done:7,exception:1,due:'08-16',batch:'资质+天气',status:'待复核',progress:64,priority:'关注'},{no:'SA-260815-026',name:'涂装线临时动火作业',code:'WP-260815-28',unit:'外协施工组',group:'涂装车间',plan:13,done:4,exception:3,due:'08-16',batch:'动火+监护',status:'待评估',progress:31,priority:'停止'},{no:'SA-260814-015',name:'仓库照明线路维护',code:'WP-260814-12',unit:'设施维修组',group:'成品仓库',plan:8,done:8,exception:0,due:'08-14',batch:'电气作业',status:'已归档',progress:100,priority:'受控'},{no:'SA-260815-031',name:'屋面光伏组件清洗',code:'WP-260815-33',unit:'新能源运维组',group:'二号厂房',plan:10,done:6,exception:1,due:'08-17',batch:'高处+天气',status:'整改中',progress:60,priority:'关注'}]
export const resources=[{code:'SAFE-EDGE-01',name:'现场安全感知网关',unit:'安全数字化组',status:'运行中',health:98,value:'146',valueUnit:'点',note:'重点区域在线率 99.1%'},{code:'MODEL-02',name:'作业风险评估模型',unit:'风险管控组',status:'复核中',health:95,value:'v2.6',valueUnit:'',note:'6 项作业触发停止门禁'},{code:'PERMIT-03',name:'电子工作票连接器',unit:'安全运营组',status:'预警',health:89,value:'73',valueUnit:'张',note:'2 张工作票资质信息待补齐'}]
export const reviews=[{no:'RV-260815-032',title:'罐区受限空间复工复核',type:'停止门禁',detail:'风险 92 · 梁安',result:'待确认'},{no:'RV-260815-011',title:'锅炉房高处作业检查',type:'控制措施',detail:'11 项措施 · 程野',result:'通过'},{no:'RV-260814-018',title:'涂装线动火许可',type:'证据补充',detail:'缺少可燃气体复测',result:'异常'}]
export const adminMetrics=[['在场作业','73','高风险作业 18 项','blue'],['停止放行','6','其中 3 项等待整改','red'],['今日闭环','29','平均用时 3.2 小时','green'],['待复核许可','8','需要安全负责人确认','orange']]
export const fieldMetrics=[['我的任务','7','3 项高风险','blue'],['今日已巡检','15','全部保留现场证据','green'],['待处理隐患','5','2 项停止作业','orange'],['感知覆盖率','96.2%','较上周提升 0.9%','slate']]
export const chartActual=[61,65,69,73,76,79,82,85,88],chartTarget=[64,68,72,76,80,84,88,92,95]
export const loads=[['储运罐区',88,'停止作业 2 项'],['涂装车间',76,'停止作业 2 项'],['能源中心',63,'停止作业 1 项'],['仓储区域',48,'停止作业 1 项']]
export const issues=[['停止','罐区氧含量复测未达放行要求','维持停止作业并加强通风','待批准'],['资质','涂装外协焊工证书即将到期','已通知承包商补充材料','处理中'],['天气','屋面阵风预计达到六级','建议调整光伏清洗窗口','需协调']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
